### ISSUE TITLE
Could not find plugin class [com.code972.elasticsearch.plugins.AnalysisPlugin]

### ISSUE THREAD

**Issue by oryband** [synhershko/elasticsearch-analysis-hebrew#16]
I'm trying to set up a Docker image with jre 1.8, Elasticsearch 2.2 and your plugin, but keep getting errors. I've no idea what am I doing wrong.

Here is the Dockerfile, note `elasticsearch:2.2` inherits [from the `java:8-jre` image](https://github.com/docker-library/elasticsearch/blob/5b2bf54e2c17a8e2e1b062ea0d071eae600bfec2/2.2/Dockerfile):
```dockerfile
FROM elasticsearch:2.2
MAINTAINER Ory Band <oryband@gmail.com>

# install hspell data files,
# hebmorph requirement
ENV HEBMORPH_VERSION 1.5.0
ENV HEBMORPH_FILE hebmorph-core-$HEBMORPH_VERSION

RUN wget -P /tmp/ https://github.com/synhershko/HebMorph/archive/$HEBMORPH_FILE.tar.gz && \
    tar -C /opt/ --strip-components 1 -xvf /tmp/$HEBMORPH_FILE.tar.gz HebMorph-$HEBMORPH_FILE/hspell-data-files && \
    chown -R elasticsearch:elasticsearch /opt/hspell-data-files && \
    rm -rf /tmp/$HEBMORPH_FILE.tar.gz

# install hebmorph plugin
RUN plugin install https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip
```
And here is the output, I've printed some helpful data before actually running elasticsearch at the bottom.
```bash
$ plugin install https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip
-> Installing from https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip...
Trying https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip ...
Downloading ......................DONE
Verifying https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed elasticsearch-analysis-hebrew into /usr/share/elasticsearch/plugins/elasticsearch-analysis-hebrew

$ ls /opt/hspell-data-files/
README   hebrew.wgz       hebrew.wgz.prefixes  hebrew.wgz.stems  prefixes.c
dmask.c  hebrew.wgz.desc  hebrew.wgz.sizes     hebrew_stop.txt

$ cat /etc/elasticsearch/elasticsearch.yml
hebrew.dict.path: /opt/hspell-data-files

# the following runs perfectly fine if I don't install the plugin
$ gosu elasticsearch elasticsearch
[2016-02-15 20:42:40,607][INFO ][node                     ] [Stingray] version[2.1.2], pid[39], build[63c285e/2016-01-27T12:57:52Z]
[2016-02-15 20:42:40,608][INFO ][node                     ] [Stingray] initializing ...
Exception in thread "main" ElasticsearchException[Could not find plugin class [com.code972.elasticsearch.plugins.AnalysisPlugin]]; nested: ClassNotFoundException[com.code972.elasticsearch.plugins.AnalysisPlugin];
Likely root cause: java.lang.ClassNotFoundException: com.code972.elasticsearch.plugins.AnalysisPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:380)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:348)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```
This also happens with ES 2.1 and the 2.1 version of your plugin.

Any idea how to make this run?

Thanks!

**Comment by oryband** [comment]
You can also see my work-in-progress branch here: https://github.com/oryband/elk-hebmorph/tree/initial-version

**Comment by oryband** [comment]
any comment please?

**Comment by synhershko** [comment]
The URL you are using - https://github.com/synhershko/elasticsearch-analysis-hebrew/archive/elasticsearch-analysis-hebrew-2.2.zip - holds the sources, not the compiled plugin. The zip file used for installation needs to be packed with the compiled version, also see https://github.com/synhershko/elasticsearch-analysis-hebrew/pull/15#issuecomment-180731443

**Comment by oryband** [comment]
@synhershko thanks for the reply. so from what i understand all versions > 1.7 haven't been released yet? if so, any chance to compile and put them up here?

thanks for the help in any case, good job!

**Comment by oryband** [comment]
same questino was asked in #17
