### ISSUE TITLE
File permissions not recursive?

### ISSUE THREAD

**Issue by odedniv** [synhershko/elasticsearch-analysis-hebrew#18]
Even though I'm prompted for file permissions I'm still seeing an error in the log on trying to access the specific files (I tried both directories).

ES 2.3.4.

```
[2016-07-24 11:26:30,207][ERROR][bootstrap                ] Exception
ElasticsearchException[Failed to load plugin class [com.code972.elasticsearch.plugins.AnalysisPlugin]]; nested: InvocationTargetException; nested: AccessControlException[access denied ("java.io.FilePermission" "/var/lib/hspell-data-files/hebrew.wgz.sizes" "read")];
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:483)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:432)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:472)
        ... 8 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/hspell-data-files/hebrew.wgz.sizes" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.FileInputStream.<init>(FileInputStream.java:127)
        at com.code972.hebmorph.hspell.HSpellLoader.<init>(HSpellLoader.java:55)
        at com.code972.hebmorph.DictionaryLoader.loadDictFromPath(DictionaryLoader.java:43)
        at com.code972.elasticsearch.plugins.DictReceiver$LoadDictAction.run(DictReceiver.java:41)
        at com.code972.elasticsearch.plugins.DictReceiver$LoadDictAction.run(DictReceiver.java:28)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.code972.elasticsearch.plugins.DictReceiver.setDictionary(DictReceiver.java:58)
        at com.code972.elasticsearch.plugins.AnalysisPlugin.<init>(AnalysisPlugin.java:18)
```

```
[2016-07-24 11:02:54,927][ERROR][bootstrap                ] Exception
ElasticsearchException[Failed to load plugin class [com.code972.elasticsearch.plugins.AnalysisPlugin]]; nested: InvocationTargetException; nested: AccessControlException[access denied ("java.io.FilePermission" "/var/lib/hebmorph/dictionary.dict/hebrew.wgz.sizes" "read")];
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:483)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:432)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:472)
        ... 8 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/hebmorph/dictionary.dict/hebrew.wgz.sizes" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.FileInputStream.<init>(FileInputStream.java:127)
        at com.code972.hebmorph.hspell.HSpellLoader.<init>(HSpellLoader.java:55)
        at com.code972.hebmorph.DictionaryLoader.loadDictFromPath(DictionaryLoader.java:43)
        at com.code972.elasticsearch.plugins.DictReceiver$LoadDictAction.run(DictReceiver.java:41)
        at com.code972.elasticsearch.plugins.DictReceiver$LoadDictAction.run(DictReceiver.java:28)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.code972.elasticsearch.plugins.DictReceiver.setDictionary(DictReceiver.java:58)
        at com.code972.elasticsearch.plugins.AnalysisPlugin.<init>(AnalysisPlugin.java:18)
        ... 13 more
```

**Comment by synhershko** [comment]
See https://docs.oracle.com/javase/7/docs/api/java/io/FilePermission.html -

> A pathname that ends in "/*" (where "/" is the file separator character, File.separatorChar) indicates all the files and directories contained in that directory.

My bad, will fix now
