### ISSUE TITLE
Can not download any version

### ISSUE THREAD

**Issue by gitli101** [synhershko/elasticsearch-analysis-hebrew#53]
Hey,

I want to test your plugin in Elasticsearch `7.x`. But as @synhershko told it's available for now just for the commercial users,
so I also tried to run the [demo](https://github.com/synhershko/elasticsearch-analysis-hebrew/tree/master/demo) with `ES_VERSION=5.3.0` and it has failed too.

By the way, this is the log of the demo creation:
```
docker build . --build-arg ES_VERSION=5.3.0 -t heb-analyzer-elasticsearch-demo
[+] Building 55.2s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.3s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.elastic.co/elasticsearch/elasticsearch:5.3.0                               5.2s
 => [internal] load build context                                                                                  0.6s
 => => transferring context: 134B                                                                                  0.2s
 => [1/5] FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0@sha256:56ac964338bc74f3874d63271433f6555648d5  40.2s
 => => resolve docker.elastic.co/elasticsearch/elasticsearch:5.3.0@sha256:56ac964338bc74f3874d63271433f6555648d55  0.1s
 => => sha256:56ac964338bc74f3874d63271433f6555648d55405a89c96f56a18dee48456eb 2.41kB / 2.41kB                     0.0s
 => => sha256:ccec59a7dd849e99addc11a9bd11b15e9addf2dff7741cf82b603d01d0ccdb54 7.72kB / 7.72kB                     0.0s
 => => sha256:3690ec4760f95690944da86dc4496148a63d85c9e3100669a318110092f6862f 2.31MB / 2.31MB                     2.2s
 => => sha256:f52154c3d3fc05d1c0f6c8d2be3b940a59557619586a3baa317f0e91a8ce52f7 51.83MB / 51.83MB                  21.6s
 => => sha256:4075cc5db14aaad6f188daa55b87f24cdfaab7bec31060ce005be019bd72dcbb 1.30kB / 1.30kB                     1.7s
 => => sha256:2d52f619a2d69b284a1e0b7a9f02ea67db4ef432aeeddfc713c942945ba694b9 33.73MB / 33.73MB                  20.5s
 => => extracting sha256:3690ec4760f95690944da86dc4496148a63d85c9e3100669a318110092f6862f                          0.5s
 => => sha256:8bb7b04253b39665f11498fa2898e02f99d825007c1aeb8fede5169bed3c774c 3.35kB / 3.35kB                     3.4s
 => => sha256:1cb5a2a95e1530c19a5dc3cad09a0f781ad65fb9ddbb01c6e0282860c54ffb01 15.52MB / 15.52MB                  12.5s
 => => sha256:e2f60cff0f2f8b934d3305030b57f0f29ab9de907508cbc98b5a78221f09cb2a 387B / 387B                        13.5s
 => => sha256:9eb2cf345f74499cc7a2750b90eb831f2e63c60e50903d791bc5fbab5acc61dd 362B / 362B                        14.4s
 => => sha256:ff68f5fa04016948ce6fae1eb0e16dfd96b9ef48a4704b00000ce6ee45b74db3 962B / 962B                        15.5s
 => => sha256:90f6e7841041dc78831226c6f949a8032d0284638a145e5051892774f94de4c7 1.32kB / 1.32kB                    16.7s
 => => extracting sha256:f52154c3d3fc05d1c0f6c8d2be3b940a59557619586a3baa317f0e91a8ce52f7                          7.0s
 => => extracting sha256:4075cc5db14aaad6f188daa55b87f24cdfaab7bec31060ce005be019bd72dcbb                          0.0s
 => => extracting sha256:2d52f619a2d69b284a1e0b7a9f02ea67db4ef432aeeddfc713c942945ba694b9                          1.8s
 => => extracting sha256:8bb7b04253b39665f11498fa2898e02f99d825007c1aeb8fede5169bed3c774c                          0.0s
 => => extracting sha256:1cb5a2a95e1530c19a5dc3cad09a0f781ad65fb9ddbb01c6e0282860c54ffb01                          0.8s
 => => extracting sha256:e2f60cff0f2f8b934d3305030b57f0f29ab9de907508cbc98b5a78221f09cb2a                          0.0s
 => => extracting sha256:9eb2cf345f74499cc7a2750b90eb831f2e63c60e50903d791bc5fbab5acc61dd                          0.0s
 => => extracting sha256:ff68f5fa04016948ce6fae1eb0e16dfd96b9ef48a4704b00000ce6ee45b74db3                          0.0s
 => => extracting sha256:90f6e7841041dc78831226c6f949a8032d0284638a145e5051892774f94de4c7                          0.0s
 => [2/5] ADD elasticsearch.yml /usr/share/elasticsearch/config/                                                   3.1s
 => [3/5] RUN chown elasticsearch:elasticsearch config/elasticsearch.yml                                           1.3s
 => [4/5] WORKDIR /usr/share/elasticsearch                                                                         0.7s
 => ERROR [5/5] RUN ./bin/elasticsearch-plugin install https://bintray.com/synhershko/elasticsearch-analysis-hebr  3.3s
------
 > [5/5] RUN ./bin/elasticsearch-plugin install https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip:
#7 1.599 -> Downloading https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
#7 2.992 Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
#7 2.993        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#7 2.993        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
#7 2.993        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
#7 2.993        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
#7 2.994        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
#7 2.994        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
#7 2.994        at java.security.AccessController.doPrivileged(Native Method)
#7 2.994        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
#7 2.995        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
#7 2.995        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
#7 2.995        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
#7 2.996        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:275)
#7 2.996        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:250)
#7 2.996        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:206)
#7 2.996        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
#7 2.997        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
#7 2.997        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
#7 2.997        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
#7 2.997        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
#7 2.998        at org.elasticsearch.cli.Command.main(Command.java:88)
#7 2.998        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
#7 2.999 Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
#7 2.999        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
#7 2.999        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
#7 2.999        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
#7 2.999        at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
#7 3.000        at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
#7 3.000        at java.net.URLConnection.getContentLength(URLConnection.java:485)
#7 3.000        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
#7 3.001        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:274)
#7 3.001        ... 9 more
------
executor failed running [/bin/sh -c ./bin/elasticsearch-plugin install https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-$ES_VERSION.zip]: exit code: 1
```

So how can I test it ?

**Comment by synhershko** [comment]
Please reach out to us https://ey.fo/he/contact
