### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by IFaniry** [synhershko/elasticsearch-analysis-hebrew#54]
Here is what I have done during the installation:

```
$ which elasticsearch-plugin
/opt/bitnami/elasticsearch/bin/elasticsearch-plugin
$ cd /opt/bitnami/elasticsearch/
$ ./bin/elasticsearch-plugin install https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
warning: usage of JAVA_HOME is deprecated, use ES_JAVA_HOME
-> Installing https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
-> Downloading https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
-> Failed installing https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
-> Rolling back https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
-> Rolled back https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.elasticsearch.plugins.InstallPluginAction.downloadZip(InstallPluginAction.java:439)
        at org.elasticsearch.plugins.InstallPluginAction.download(InstallPluginAction.java:315)
        at org.elasticsearch.plugins.InstallPluginAction.execute(InstallPluginAction.java:230)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:84)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
```

I get a 403 error.

Is the link to [https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip](https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip) broken?
How can I get the Hebrew analyzer, please?

**Comment by synhershko** [comment]
Please reach out to us https://ey.fo/en/contact
